# /usr/share/doc/lazygit/Config.md

git:
  paging:
    colorArg: always
    # delta won't detect theme in lazygit https://github.com/jesseduffield/lazygit/pull/3420
    # pager: delta --paging=never --detect-dark-light=auto
    pager: delta --paging=never --dark
    # useConfig: true
promptToReturnFromSubprocess: false

customCommands:
  # https://github.com/jesseduffield/lazygit/pull/3104
  # TODO: menu bind
  - key: "y"
    prompts:
      - type: "menu"
        title: "yank diff"
        options:
          - name: "apply"
            value: "xsel -ob | git apply -"
          - name: "unstage diff"
            value: "git diff | xsel -ib"
          - name: "staged diff"
            value: "git diff --staged | xsel -ib"
          - name: "all diff"
            value: "git diff HEAD | xsel -ib"
    command: "{{index .PromptResponses 0}}"
    context: "localBranches"
  - key: "y"
    command: "cat {{ .SelectedPath }} | xsel -ib"
    context: "files"
    description: "copy file content to clipboard"
    subprocess: true

# TODO: fix hang when xdg-open use terminal as opener
# or hang on first open?
keybinding:
  universal:
    openFile: ""

os:
  edit: '[[ -z "$NVIM" ]] && { nvim {{filename}} &>/dev/tty; true; } || { nvim -u NONE --server $NVIM --remote-expr "execute(\"ToggleTerm | e {{filename}}\")"; }'
  editAtLine: '[[ -z "$NVIM" ]] && { nvim +{{line}} {{filename}} &>/dev/tty; true; } || { nvim -u NONE --server $NVIM --remote-expr "execute(\"ToggleTerm | e {{filename}} | call cursor({{line}}, 0)\")"; }'
  # https://github.com/jesseduffield/lazygit/issues/996
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  editInTerminal: true
  # open: "xdg-open {{filename}} >/dev/null &"
