# /usr/share/doc/lazygit/Config.md

gui:
  showFileTree: false
git:
  paging:
    colorArg: always
    # delta won't detect theme in lazygit https://github.com/jesseduffield/lazygit/pull/3420
    # pager: delta --paging=never --detect-dark-light=auto
    pager: delta --paging=never --dark
    # useConfig: true
  preferRemotes:
    - upstream
    - origin
promptToReturnFromSubprocess: false

customCommands:
  # https://github.com/jesseduffield/lazygit/pull/3104
  - key: "y"
    prompts:
      - type: "menu"
        title: "yank diff"
        options:
          - name: "apply"
            value: "xsel -ob | git apply -"
          - name: "unstage diff"
            value: "git diff | xsel -ib"
          - name: "staged diff"
            value: "git diff --staged | xsel -ib"
          - name: "all diff"
            value: "git diff HEAD | xsel -ib"
    command: "{{index .PromptResponses 0}}"
    context: "localBranches"
  - key: "y"
    command: "cat {{ .SelectedPath }} | xsel -ib"
    context: "files"
    description: "copy file content to clipboard"
    subprocess: true
  - key: "<c-j>"
    command: "git absorb -f -F"
    context: "files"
    description: "one commit"
  - key: "<c-k>"
    command: "git absorb -f -Fw"
    context: "files"
    description: "git absorb -Fw"

# fix hang when xdg-open use terminal as opener
# or hang on first open?
keybinding:
  universal:
    openFile: ""

os:
  openLink: 'xdg-open {{link}} & >/dev/null'
  copyToClipboardCmd: printf "\033]52;c;$(printf {{text}} | base64)\a" > /dev/tty

notARepository: 'quit'
