#!/usr/bin/env sh

# /usr/share/doc/bspwm/examples/sxhkdrc
# don't use xdotool, maybe collide with kmonad

# control
super + {_, ctrl +} r
	{pkill -USR1 -x sxhkd, bspc wm -r; pkill polybar; polybar -r;}
super + {_, ctrl +} q
	bspc {node -c, quit}

# navigate
super + {j, k}
	bspc node -f {next, prev}.local.!hidden.window
super + ctrl + {j, k}
	bspc desktop -f {next, prev}.local
# super + {e, h}
# 	bspc {desktop -f last, node -f last.local}
super + e
	bspc desktop -f last
super + {o, i}
	bspc wm -h off; \
	bspc node -f {older, newer}; \
	bspc wm -h on
super + ctrl + {_, shift + } {i, o}
	bspc {desktop -f, node -d} "^{1,7}"

# super + ctrl + {u,i}
# 	NEX=$((((7 {+, -} 3 + $(bspc query -D -d focused --names)) % 7))); \
# 	if [[ $NEX == 0 ]]; then NEX=7 fi; \
# 	bspc desktop -f \^$NEX

# move
super + l
	(bspc node -f biggest.window.local && \
		bspc node -f last.window.local && \
		bspc node -s biggest.window.local) || \
	(bspc node -f last.window.local && bspc node -s biggest.window.local)
super + shift + {j, k}
	bspc node -d {next, prev} --follow
super + ctrl + shift + {j, k}
	bspc node -d {next, prev}
# super + shift + {{j, k}, ctrl + {j, k}}
# 	bspc node -d {{next, prev} --follow, {next, prev}}
super + alt + {j, k}
	bspc desktop -s {next, prev} -f; bspc monitor -d 1 2 3 4 5 6 0
# super + {_, ctrl +} g
# 	bspc node -s {next, prev}.window.local
# super + alt + {p, b, w, e}
# 	bspc node -f @{parent, brother, first, second}

# tag num
super + {1-6, 0}
	bspc desktop -f '^{1-7}'
super + shift + {1-6, 0}
	bspc node -d '^{1-7}' --follow
super + ctrl + {1-6, 0}
	bspc node -d '^{1-7}'

# status switch
super + m
	bspc desktop -l next

# hide
# super + {_, alt + } v
# 	bspc node {-g hidden, ${bspc query -N -n .hidden | tail -n1} -g hidden=off}
super + d
	sh $XDG_CONFIG_HOME/sxhkd/scripts/toggle-hidden.sh

super + alt + {m, l, s, p}
	bspc node -g {marked, locked, sticky, private}

super + shift + f
	bspc node -t \~floating
super + y
	bspc node -t \~pseudo_tiled
super + shift + y
	bspc node -t \~tiled

# resize
super + ctrl + {h, l}
	bspc node -z {left -20 0 || bspc node -z right -20 0, \
				right 20 0 || bspc node -z left 20 0}

super + shift + {m, comma, period, slash}
		bspc node -z {left -20 0 || bspc node -z right -20 0, \
					bottom 0 20 || bspc node -z top 0 20, \
				top 0 -20 || bspc node -z bottom 0 -20, \
				right 20 0 || bspc node -z left 20 0}
super + shift + {u, i, o, p}
	bspc node -z {right -20 0 || bspc node -z left -20 0, \
				top 0 20 || bspc node -z bottom 0 20, \
				bottom 0 -20 || bspc node -z top 0 -20, \
				left 20 0 || bspc node -z right 20 0}

# misc
# rotation
super + shift + r
    bspc node @/ -R 90
super + shift + e
    bspc node @parent -R 90
super + ctrl + t
	sh $XDG_CONFIG_HOME/sxhkd/scripts/toggle-polybar.sh
# super + shift + c
# 	bsp-layout set tall

# launch
super + b
	~/bin/tabexec.sh alacritty msg create-window
super + n
	alacritty --working-directory ~
super + s
	~/bin/tabexec.sh chromium
super + ctrl + s
	chromium
super + semicolon
	rofi -show drun -matching fuzzy
super + apostrophe
	~/bin/tabexec.sh eval "$(dmenu_path | rofi -dmenu)"
	# ~/bin/tabexec.sh rofi -show run -matching fuzzy
	# id=$(bspc query -N -n focused); tabc autoattach $id; rofi -show run -matching fuzzy; sleep 0.3; tabc autoattach $id;
super + w
	rofi -show window -matching fuzzy
super + backslash
	rofi -show keys -matching fuzzy
super + {_, ctrl + } slash
	alacritty --working-directory ~ --command nvim {_, $XDG_CONFIG_HOME/sxhkd/sxhkdrc}
super + period
	alacritty --working-directory ~/notes --command nvim todo.md
	# FIXME kitty --detach --working-directory ~/notes nvim ~/notes/todo.md
super + t
	dex --term alacritty /usr/share/applications/vifm.desktop
super + {z, x, c}
	{scrcpy, walrnd, darkman toggle}
super + p
	CM_LAUNCHER=rofi clipmenu

super + {minus, equal}
	dbus-send --print-reply --dest=org.mpris.MediaPlayer2.com.gitee.gmg137.NeteaseCloudMusicGtk4 /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.{Previous,Next}
super + BackSpace
	dbus-send --print-reply --dest=org.mpris.MediaPlayer2.com.gitee.gmg137.NeteaseCloudMusicGtk4 /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
# super + t
# 	tabc create $(bspc query -N -n focused)
# 	id=$(bspc query -N -n); \
# 	[[ "$(tabc printclass $id)" == "tabbed" ]] \
# 	&& tabc detach $id \
# 	|| tabc create $id
	## tabc autoattach $(bspc query -N -n focused)

super + Tab
	dunstctl close-all

super + plus
	bspc node @/ --equalize
super + underscore
	bspc node @/ --balance

# proxy via kmonad
super + {F1, F2}
	sound-control {down, up}
super + {F3, F4}
	light-control {down, up}
super + {F5, F6, F7, F8}
	xrandr -o {left, right, normal, inverted}
super + F9
	flameshot gui
super + F10
	picgo -p http://127.0.0.1:7890 u | tail -n1 | tr -d "\n" | xsel -b && notify-send finish
super + shift + bracketleft
	flameshot gui -r | imgur.sh
super + bracketright
	slip --stop || slip --gif
super + F11
	~/bin/toggle-touchpad.sh
