#!/usr/bin/env bash

# main(){
# 	if [[ "$biggest" = "$focused" ]]
# 	then get_smaller
# 	else move_biggest; fi
# }
#
# read_leafs(){
# 	IFS=$'\n' read -r -d '' -a leafs <\
# 	<(bspc query -N -n .leaf.local.!hidden.tiled)
# }
#
# query_nodes(){
# 	focused="$(bspc query -N -n focused.local.!hidden.window)"
# 	biggest="$(bspc query -N -n biggest.local.!hidden.window)"
# }
#
# get_smaller(){
# 	bspc node -s "${leafs[1]}"
# 	bspc node -f biggest.local.!hidden
# }
#
# move_biggest(){
# 	bspc node -n biggest.local.!hidden -s "${leafs[1]}"
# 	bspc node -s biggest.local.!hidden --follow
# }
#
# read_leafs
# query_nodes
# main

f="${1:-$(bspc query -N -n)}"
b="$(bspc query -N -n biggest.local)"
m="$(bspc query -N -n last.marked.local)" ||
    m="$(bspc query -N -n any.marked.local)"
[ "$f" = "$b" ] && {
    set -- "${m:-$(bspc query -N -n last.local)}" "$f"
} || {
    [ -n "$m" ] && bspc node "$m" -g marked=off
    set -- "$f" "$b"
}
bspc node "$1" -s "$2" -g marked=off -f &&
    bspc node "$2" -g marked=on
