#!/bin/sh
{
  builtin pwd # ensure cwd is the first one
  fd . -a -d 1 --type d -I | rg '/$' -r ''
  zoxide query -l
  fd . ~/.local/share/nvim/lazy/ ~/.local/share/fish/plug/ ~/dot/ ~/b/ -d 1 --type directory -a | rg '/$' -r ''
} | awk '!_[$0]++' | tail -n+2
