#!/bin/sh

# git clone https://github.com/phanen/neovim ~/b/neovim
# git remote add upstream http://github.com/neovim/neovim
# git fetch
# git branch patch origin/patch
# git checkout patch
# git branch --set-upstream-to=upstream/master
# ln -sf ~/b/n{eo,}vim

VIM=$(basename "$0")
case "$VIM" in
nvim) ARG=--luamod-dev ;;
vim) ROOT=$HOME/b/vim ;;
esac

ROOT=$HOME/b/$VIM
VIM_BIN=$(PATH=$ROOT/build/bin:/bin/:/usr/bin:/run/current-system/sw/bin:$PATH command -v "$VIM") || exit $?
case "$VIM_BIN" in
"$(realpath -s "$0")") exit 1 ;; # recursion
"$ROOT/build/bin/$VIM") VIMRUNTIME=$ROOT/runtime ;;
esac

SESSION=/tmp/reload-$VIM.vim
MAGIC_S=123 # reload session
MAGIC_R=124 # fresh restart
MAGIC_A=125 # restart with args
SAVE_CWD_HERE=${SAVE_CWD_HERE:-$(mktemp)}

# https://vi.stackexchange.com/questions/36957/update-all-of-the-unsaved-buffers-at-vim
CMD="+\
nn <nowait> sd <cmd>sil!wa!\|mks!$SESSION\|cq!$MAGIC_S<cr>|\
nn <nowait> s<space> <cmd>sil!wa!\|mks!$SESSION\|cq!$MAGIC_R<cr>|\
nn <nowait> sa <cmd>sil!wa!\|mks!$SESSION\|cq!$MAGIC_A<cr>|\
nn <nowait> sc <cmd>quit!<cr>|\
nn <nowait> se <cmd>e \$MYVIMRC<cr>|\
nn <nowait> <c-s> <cmd>quit!<cr>|\
au VimLeave * ++once call writefile([getcwd()], '$SAVE_CWD_HERE')"

# $ARGS then $@: if `--` in "$@"
# "" is required for sh -c 'nvim xx'
# not sure how "" expand to args...
# https://unix.stackexchange.com/questions/415990/how-can-i-expand-a-quoted-variable-to-nothing-if-its-empty
VIMRUNTIME=$VIMRUNTIME $VIM_BIN "$CMD" ${ARG:+"$ARG"} "$@"
STATUS=$?

NEW_DIR=$(cat "$SAVE_CWD_HERE")
if [ -n "$NEW_DIR" ] && [ "$PWD" != "$NEW_DIR" ]; then
  cd "$NEW_DIR" || exit 1
fi

case $STATUS in
"$MAGIC_S") exec $0 -S "$SESSION" ;;
"$MAGIC_R") exec $0 ;;
"$MAGIC_A") exec $0 "$@" ;;
*) exit $STATUS ;;
esac
