#!/bin/sh

# normal enter...
if command -v ~/b/neovim/build/bin/nvim 1>/dev/null 2>/dev/null; then
  VIMRUNTIME=~/b/neovim/runtime ~/b/neovim/build/bin/nvim "$@"
else
  /bin/nvim "$@"
fi

# rebirth if needed
test $? != 123 && exit

session_cmd="so /tmp/reload.vim"
while true; do
  if command -v ~/b/neovim/build/bin/nvim 1>/dev/null 2>/dev/null; then
    VIMRUNTIME=~/b/neovim/runtime ~/b/neovim/build/bin/nvim +"$session_cmd"
  else
    /bin/nvim +"$session_cmd"
  fi
  test $? != 123 && exit
done
