#!/bin/sh

volume=$(pulsemixer --get-volume | awk '{print $1}')
setter="pulsemixer --set-volume"
case "$1" in
  +) $setter $((volume+5));;
  -) $setter $((volume-5));;
  *) echo "Usage: $0 +|-"
     exit 1
     ;;
esac
