# https://docs.atuin.sh/configuration/config/

show_help = false

# inline ui, don't fullscreen
inline_height = 20
invert = true

# preview long command
show_preview = true
max_preview_height = 6

# TODO: ctrl-i donnot work, so we don't preselect it now
enter_accept = false

## TODO: maybe less candidate, and i don't want use number
## use ctrl instead of alt as shortcuts
ctrl_n_shortcuts = true
