# https://docs.atuin.sh/configuration/config/

show_help = false

# inline ui, don't fullscreen
inline_height = 20
invert = true

# preview long command
show_preview = true
max_preview_height = 2

enter_accept = false    # TODO: ctrl-i confirm, enter -> run-with-no-confirm
ctrl_n_shortcuts = true # use ctrl+x instead alt+x to select

sync_address = "http://ali:18888"
sync_frequency = "10m"

[sync]
records = true

[dotfiles]
enabled = true
