[[manager.prepend_keymap]]
on = ["m"]
# run  = "plugin test"
run = "plugin test --args='hello world'"
desc = "test"

[[manager.prepend_keymap]]
on = ["l"]
run = "plugin l"
desc = "Enter the child directory, or open the file"
