# https://github.com/sxyazi/yazi/blob/latest/yazi-config/preset/keymap.toml
[manager]
ratio = [3, 5, 10]

[opener]
edit = [
  { run = '[[ -z "$NVIM" ]] && { nvim "$@" &>/dev/tty; true; } || { nvim -u NONE --server $NVIM --remote-expr "execute(\"ToggleTerm | e "$@"\")"; }', block = true, for = "unix" },
]
