#!/bin/sh
bspc monitor -d 0 1 2
bspc config border_width        5
bspc config focused_border_color \#00ff00
bspc config window_gap          0
bspc config focus_follows_pointer true
bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true
echo "0 1 2 " | tr ' ' '\n' | xargs -I@ bsp-layout set tall @
