#!/bin/sh

# /usr/share/doc/bspwm/examples/bspwmrc

# TODO to started from tty or wm, that's a question...

# _bootstrap() { if ! pgrep "$1"; then eval "$@" 2>&1 >/dev/null; fi }
# _bootstrap kmonad ~/.config/kmonad/kmonad.kbd &
# _bootstrap sxhkd -a Tab &
# _bootstrap polybar -r &
# _bootstrap fcitx5 -d &
# _bootstrap udiskie &
# _bootstrap picom &

# unnecessary
# pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config border_width        6
bspc config window_gap          0

bspc config focused_border_color \#00ff00

bspc config focus_follows_pointer true

bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Bochs state=tiled

bspc rule --add idea state=floating rectangle=xH+X+Y
# bspc config automatic_scheme spiral
# bspc config initial_polarity first_child
# bspc config removal_adjustment true
#
# # how much of the screen the "master" takes by default
# bspc config split_ratio 0.7

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
