#!/usr/bin/env bash

test -z "$joshuto_wrap_id" && exit 1;

path="$1"       # Full path of the previewed file
x="$2"          # x coordinate of upper left cell of preview area
y="$3"          # y coordinate of upper left cell of preview area
width="$4"      # Width of the preview pane (number of fitting characters)
height="$5"     # Height of the preview pane (number of fitting characters)


# Find out mimetype and extension
mimetype=$(file --mime-type -Lb "$path")
extension=$(/bin/echo "${path##*.}" | awk '{print tolower($0)}')

PCACHE="$HOME/.cache/joshuto/$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$path")" | sha256sum)"

plain_handler() {
    case "$mimetype" in
        image/png | image/jpeg)
            show_image "$path" $x $y $width $height
            # we will not exit here, since we want always hook remove
            ;;
        application/pdf)
            [ ! -f "${PCACHE}.jpg" ] && \
                    pdftoppm -jpeg -f 1 -singlefile "$path" "$PCACHE"
            show_image "$PCACHE".jpg $x $y $width $height
            ;;
        *)
            remove_image
    esac
}

icat_handler() {
    case "$mimetype" in
        image/*)
            # kitty +kitten icat --clear
            kitty +kitten icat \
                    --transfer-mode file \
                    --place "${width}x${height}@${x}x${y}" \
                    "${path}"
            ;;
        # application/pdf)
        #
        #     ;;
        *)
            kitty +kitten icat \
                        --transfer-mode=file \
                        --clear 2>/dev/null
                    ;;
    esac


}

# test of string and num differ.... https://wangdoc.com/bash/condition
if [[ $TERM == "xterm-kitty" ]]; then
    icat_handler
else
    plain_handler
fi

# [[ $TERM -eq "xterm-kitty" ]] && icat_handler || plain_handler
