prSections:
  - title: Owner
    filters: is:open owner:phanen
  - title: Author
    filters: is:open author:@me
  - title: Review-Requested
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open -author:@me involves:@me
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open -author:@me involves:@me
defaults:
  prsLimit: 20
  issuesLimit: 20
  preview:
    open: true
    width: 100
keybindings:
pager:
  diff: less
