#!/bin/bash

# _bootstrap(){ if ! pgrep "$1'; then eval " $@" if }
# _bootstrap sxhkd &
# _bootstrap polybar &
# _bootstrap fcitx5 -d
# _bootstrap udiskie &

sxhkd &
polybar &
fcitx5 -d
udiskie &
picom &
