[general]
ipc_socket = true
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#767676"
blue = "#1a8fff"
cyan = "#14ffff"
green = "#23fd00"
magenta = "#fd28ff"
red = "#f2201f"
white = "#ffffff"
yellow = "#fffd00"

[colors.normal]
black = "#000000"
blue = "#0d73cc"
cyan = "#0dcdcd"
green = "#19cb00"
magenta = "#cb1ed1"
red = "#cc0403"
white = "#dddddd"
yellow = "#cecb00"

[colors.primary]
background = "#000000"
foreground = "#dddddd"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

[debug]
highlight_damage = false
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = false
size = 15

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Comma"
mode = "~Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi|~Search"

[terminal.shell]
program = "/bin/fish"

[window]
opacity = 0.9

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
